### PR TITLE
Improved Bibliography Formatting

### PR DESCRIPTION
**Pull request by SECtim**
Note: This PR depends on #4.

Previously, replacement of placeholders in the formatting string used the fields of the actual bib entry. This leaves placeholders in the output whenever a field is in the format string, but not in the entry.
This PR turns the logic around: The format string is parsed for placeholders and these are either replaced by the corresponding value from the entry or removed if the entry does not contain a corresponding value.

Furthermore, the format string often contains punctuation, e.g., commas, between placeholders. These should of course also be removed when a placeholder cannot be "filled" with data. Hence, this PR also introduces a slightly more complex but also much more flexible syntax for format strings:

- Literals (i.e., stuff that will always be printed) are given as usual
- Placeholders for entry data are written in all UPPERCASE and enclosed in `@`, e.g., `@title@`.
- Each placeholder for entry data must be given inside a group. Groups are delimited by braces, and each group contains exactly one placeholder. _Groups cannot be nested._ A group only produces output if its placeholder has corresponding data in the currently processed entry.
- Placeholders for language-specific strings are given as all lowercase, and also enclosed in `@`, e.g., `@editorabbrev@`

Example for `@inproceedings`:
```
{@AUTHOR@}{ (@YEAR@)}{: "@TITLE@"}{, in: <em>@BOOKTITLE@</em>}{, @EDITOR@ (@editorabbrev@)}{, @pagesabbrev@ @PAGES@}{. @PUBLISHER@}{, @ADDRESS@}.{ @NOTE@}{ <a href="https://doi.org/@DOI@">(DOI)</a>}{ <a href="@URL@">(Link)</a>}
```
i.e., an entry
```bibtex
@inproceedings{proverif-xor-kuesters-2008,
  author = {K\"{u}sters, Ralf and Truderung, Tomasz},
  title = {Reducing Protocol Analysis with XOR to the XOR-Free Case in the Horn Theory Based Approach},
  year = {2008},
  publisher = {Association for Computing Machinery},
  url = {https://doi.org/10.1145/1455770.1455788},
  doi = {10.1145/1455770.1455788},
  booktitle = {Proceedings of the 15th ACM Conference on Computer and Communications Security},
  pages = {129–138},
  numpages = {10},
  editor = {Syverson, Paul and Jha, Somesh},
}
```
gets rendered as (note that even though the entry does not have a `note` field, no space is added, because the whole group `{ @NOTE@}` is suppressed):
image

### CODE REVIEW

**Comment by tillbiskup** [comment]
Just from looking at your detailed description at the top (thanks a lot for that!), this looks very promising.
Turning the logic for search&replace around (basically from its head to its feet) is an excellent idea.
Just to mention: The origins of the plugin are in my rather distant programming past, and the code "just worked" and was otherwise dormant for years while I was busy not programming with PHP. :-)

**Review by SECtim — COMMENTED** [review]
Just to be clear on this: I am painfully aware of how commit eb49f923c1f2bae5efc3d6d5df4da8bfbf3238c1 increases the complexity of the already quite complex parsing algorithm. However, short of coming up with a new parsing algorithm, I cannot think of a cleaner way to do this (and a new algorithm will probably end up just as complex since BibTeX "allows" so much, e.g., regarding field-value delimiters).

**Comment by SECtim** [comment]
Ready to be merged from my side. This also fixes several PHP warnings, e.g., regarding undefined array keys during option parsing.

**Comment by tillbiskup** [comment]
Apologies for the long silence... I'll have a look at this as soon as possible (hopefully within the next ten days or so) and merge it. However, as far as I understand, the change in logic is a breaking change? And it would definitely requite an updated documentation?

**Comment by SECtim** [comment]
Yes, this would indeed be a breaking change (regarding the plugin configuration, any BibTeX can of course be kept as-is). However, migration of existing settings should be pretty simple. While one could add a setting to switch between the old and the new behavior, I feel like the old behavior is quite counter-intuitive in that, e.g., `PUBLISHER` would show up in the "rendered" entry as `PUBLISHER` if an entry does not have that field.
Also, such a setting of course further increases code complexity.

As for migration, it seems that Dokuwiki does not have an explicit configuration migration API for plugins during updates (I had a quick look at the docs, but maybe I've overlooked something).
However, if the current format string for a given entry type is the "old" default (and has never been changed by the user, i.e., no corresponding setting stored in `conf/local.php`), Dokuwiki should already switch to the new default.
For settings in `conf/local.php`, we could detect an "old" format string from its lack of "new" placeholders (assuming that nobody wants to have a fixed output for a particular entry type). If that is the case, we may, e.g., silently use the new default (probably a bad idea), or inform (admin) users that they have to adapt their configuration (though I am not sure how to implement that, there does not seem to be an API for such messages).

I would have updated the documentation as part of this PR, but it seems that the docs are not part of the repository. In case I can help with documentation, I am willing to do so.

**Comment by tillbiskup** [comment]
Thanks a lot for your detailed reply.

Regarding the migration: Probably the best bet would be to clearly tell potential users that they need to update their config (if they changed it) on the Dokuwiki page of the plugin. As you say, there seems to be no API for those cases.

Documentation: Well... the plugin clearly predates my current way of writing code... ;-) I'll try to add the documentation asap to the repo. Afterwards, any contributions are warmly welcome (and I'll try to be more responsive this time).

**Comment by tillbiskup** [comment]
I've merged your commits, as you probably have seen already.

Regarding documentation: Do you think adding the current DokuWiki plugin page in a "docs" directory would make some sense? DokuWiki plugins tend to be documented in DokuWiki itself... hence, Markdown or else seems not to make too much sense. And including the documentation in the plugin repository  (although something sensible in my eyes) seems not common for DokuWiki plugins. Just let me know your thoughts. Then I would add some documentation to the repo and would be happy to receive your pull requests, particularly describing the new config syntax.

**Comment by SECtim** [comment]
Thanks for merging! I don't have much experience with the development of Dokuwiki plugins either, but checking in the Dokuwiki documentation page(s) along with the code feels like the most sensible option to me; at least if there's an automated (or at least: simple & fast) process for you to update the actual wiki page with what is checked in to this repository.

I'd be happy to contribute to the docs regarding the syntax! If you choose to not check in the Dokuwiki page, I could still provide some Dokuwiki-formatted paragraphs (assuming that your wiki instance does nothing too fancy in terms of syntax modifications).

**Pull request merged**
